CREATE DATABASE IF NOT EXISTS `outbreak`;
USE `outbreak`;

CREATE TABLE `users` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Identifier` VARCHAR(50) NOT NULL,
	`Nickname` TINYTEXT NOT NULL DEFAULT 'Unknown',
	`Name` TINYTEXT NULL DEFAULT NULL,
	`Date Of Birth` VARCHAR(10) NULL DEFAULT NULL,
	`Sex` VARCHAR(12) NULL DEFAULT NULL,
	`Group` VARCHAR(50) NULL DEFAULT NULL,
	`Faction` VARCHAR(50) NULL DEFAULT NULL,
	`Money` LONGTEXT NULL DEFAULT NULL,
	`Inventory` LONGTEXT NOT NULL DEFAULT '{}',
	`Skin` LONGTEXT NULL DEFAULT NULL,
	`Position` LONGTEXT NULL DEFAULT NULL,

	PRIMARY KEY (`ID`)
);

CREATE TABLE `items` (
	`Name` VARCHAR(50) NOT NULL,
	`Label` VARCHAR(50) NOT NULL,
	`Description` TEXT(65535) NULL DEFAULT 'No Description.',
	`Weight` FLOAT(12) NOT NULL DEFAULT '0',
	`Limit` INT(11) NOT NULL DEFAULT '1',
	PRIMARY KEY (`Name`) USING BTREE
);