CREATE DATABASE IF NOT EXISTS `outbreak`;
USE `outbreak`;

CREATE TABLE `users` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Identifier` VARCHAR(50) NOT NULL,
	`Nickname` TINYTEXT NOT NULL DEFAULT 'Unknown',
	`Name` TINYTEXT NULL DEFAULT NULL,
	`Date Of Birth` VARCHAR(10) NULL DEFAULT NULL,
	`Sex` VARCHAR(12) NULL DEFAULT NULL,
	`Group` VARCHAR(50) NULL DEFAULT NULL,
	`Faction` VARCHAR(50) NULL DEFAULT NULL,
	`Money` LONGTEXT NULL DEFAULT NULL,
	`Inventory` LONGTEXT NULL DEFAULT NULL,
	`Skin` LONGTEXT NULL DEFAULT NULL,
	`Position` LONGTEXT NULL DEFAULT NULL,

	PRIMARY KEY (`ID`)
);

CREATE TABLE `items` (
	`Name` VARCHAR(50) NOT NULL,
	`Label` VARCHAR(50) NOT NULL,
	`Weight` VARCHAR(1) NOT NULL DEFAULT 1,

	PRIMARY KEY (`Name`)
);