CREATE DATABASE IF NOT EXISTS `outbreak`;
USE `outbreak`;

CREATE TABLE `users` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Identifier` VARCHAR(50) NOT NULL,
	`Nickname` VARCHAR(20) NOT NULL DEFAULT 'Unknown',
	`IP` VARCHAR(15) NOT NULL,
	`Name` VARCHAR(20) NULL DEFAULT NULL,
	`Sex` VARCHAR(6) NULL DEFAULT NULL,
	`Skin` VARCHAR(50) NULL DEFAULT NULL,

	PRIMARY KEY (`ID`)
);